# Generated by Django 5.1.7 on 2025-03-28 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
    ]
