# Generated by Django 5.1.6 on 2025-04-08 18:06

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),  # Enable the pg_trgm extension
    ]
