# Generated by Django 5.1.6 on 2025-05-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_postgres_setpup'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseunit',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='staff',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], default='undergraduate', max_length=32),
        ),
        migrations.AddField(
            model_name='staff',
            name='course_units',
            field=models.ManyToManyField(related_name='staff', to='core.courseunit'),
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='core.course'),
        ),
        migrations.RemoveField(
            model_name='courseunit',
            name='code',
        ),
    ]
