# Generated by Django 5.1.6 on 2025-05-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_courseunit_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseunit',
            name='code',
            field=models.CharField(default='default', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
