# Generated by Django 5.1.6 on 2025-05-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_courseunit_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_id',
            field=models.UUIDField(default=1234324324, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='student_no',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
