# Generated by Django 5.1.6 on 2025-05-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_department_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('faculty', 'name')},
        ),
    ]
