# Generated by Django 5.1.6 on 2025-05-23 13:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_department_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='reference_no',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
