# Generated by Django 5.1.6 on 2025-05-23 13:09

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("core", "Issue")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["reference_no"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_issue_reference_no'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
