# Generated by Django 5.1.6 on 2025-05-23 13:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20250523_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='reference_no',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
